### ISSUE TITLE
License of OpenBSP?

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [osman-turan/OpenBSP-Legacy#1]
Hi there,

I wonder, what the license of your OpenBSP software is?

Thanks.

**Comment by osman-turan** [comment]
Hi @Free-Pascal-meets-SDL-Website,
I've just updated the repository to include a detailed readme file and a license file (see #2). It's MIT licensed. I am just curious and would like to know why did you ask the license?

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Hi @osman-turan,

thank you very much for updating the information so immediately. Also I 
really like the choice of the license (not a restrictive one). As a 
sidenote, I'm really impressed by this project (and know about it a long 
time to be honest)!

Recently, I have been playing around with the GoldSrc Bsp format 
(Valve's variant of id's Quake2 format; check this 
https://www.freepascal-meets-sdl.net/the-goldsrc-bsp-loader/ if you 
like) and I thought loosly about new projects which used OpenBSP. But 
unless I knew about the license I stopped myself of thinking about 
projects involving OpenBSP :-).

Unfortunately, if something will come from this, I can't tell you now, 
though.

**Comment by osman-turan** [comment]
Hi @Free-Pascal-meets-SDL-Website,
Thank you for your interest and kind response. I look forward to hearing from you about exciting OpenBSP related projects.
